#!/bin/bash
# Author: fkolacek@redhat.com
# Description:
# Version: 1.0

LOGDIR="/var/log/sumchecker"

if [ ! -d "${LOGDIR}" ]; then
  echo "[!] Log directory does not exist!" >&2
  exit 2
fi

LOGFILES=$(ls "${LOGDIR}" | grep -v out)

if [[ $(echo "${LOGFILES}" | wc -w ) -le 1 ]]; then
  echo "[!] Not enough scans to compare!" >&2
  exit 2
fi

FILES=(${LOGFILES})
LOGNEW="${FILES[-1]}"
LOGOLD="${FILES[-2]}"

echo "[*] Comparing scans ${LOGDIR}/{${LOGNEW},${LOGOLD}}"

# diff "${LOGDIR}/${LOGNEW}" "${LOGDIR}/${LOGOLD}"
OLDFILE=$(cat "${LOGDIR}/${LOGOLD}")
RETVAL=0

while read line; do
  SUM=$(echo "${line}" | awk '{print $1}')
  FILE=$(echo "${line}" | awk '{$1=""; print $0}')
  ESC_FILE=$(printf '%s\n' "$FILE" | sed 's/[\$\+\-\^]/\\&/g')
  SUM2=$(echo "${OLDFILE}" | egrep " ${ESC_FILE}$" | head -n1 | awk '{print $1}')
  if [ -z "${SUM2}" ]; then
    echo "[*] New file: ${FILE}"
    RETVAL=1
  elif [ "${SUM}" != "${SUM2}" ]; then
    echo "[!] Sum mismatch: ${FILE}"
    RETVAL=1
  fi
done < <(cat "${LOGDIR}/${LOGNEW}")

echo "[*] Comparison finished"

exit ${RETVAL}
