#!/bin/bash

CURL=$(which curl)
XCLIP=$(which xclip)
DEST="http://example.com/"
TOKEN="000000000000000000000000000000000"

if [ -z "${CURL}" ]; then
  echo "Cannot find curl in PATH"
  exit 1
fi

if [ -z "${XCLIP}" ]; then
  echo "Cannot find xclip in PATH"
  exit 1
fi

if [ -z "$1" ]; then
  echo "Usage: $0 [link] [tags..]"
  exit 1
fi

if [ -f /etc/uprc ]; then
  source /etc/uprc
fi

if [ -f ~/.uprc ]; then
  source ~/.uprc
fi

LINK="$1"

if [ ! -z "$2" ]; then
  TAGS="$2"
else
  TAGS=""
fi

OUT=$(${CURL} -s -F link="${LINK}" -F token="${TOKEN}" -F tags="${TAGS}" "${DEST}")

echo "${OUT}" | ${XCLIP} -selection clipboard

echo "${OUT}"

exit 0
